#include "graphics.h"
#include "gba.h"
#include "images/sprites.h"
#include "logic.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"
static void drawSprites(void);
volatile OamEntry shadow[128];
volatile OamEntry* tileSelector = &shadow[0];
volatile OamEntry* menuAttack = &shadow[4];
volatile OamEntry* menuItem = &shadow[2];
volatile OamEntry* menuWait = &shadow[3];
volatile OamEntry* menuSelector = &shadow[1];
void hideSprites(void) {
    for(int i = 0; i < 128; i++) {
        shadow[i].attr0 = ATTR0_HIDE;
    }
    drawSprites();
}
void graphicsInit(void) {
    DMA[3].src = sprites_palette;
    DMA[3].dst = SPRITEPAL;
    DMA[3].cnt = SPRITES_PALETTE_LENGTH | DMA_ON;

    DMA[3].src = sprites;
    DMA[3].dst = &CHARBLOCKBASE[5];
    DMA[3].cnt = SPRITES_LENGTH | DMA_ON;


    for(int i = 0; i < 128; i++) {
        shadow[i].attr0 = ATTR0_HIDE;
    }
    

    tileSelector->attr2 = TILESELECTOR_PALETTE_ID | TILESELECTOR_ID;
    menuAttack->attr2 = ATTACKMENU_PALETTE_ID | ATTACKMENU_ID;
    menuItem->attr2 = ITEMMENU_PALETTE_ID | ITEMMENU_ID;
    menuWait->attr2 = WAITMENU_PALETTE_ID | WAITMENU_ID;
    menuSelector->attr2 = MENUSELECTOR_PALETTE_ID | MENUSELECTOR_ID;
    
}
static void drawTileSelector(int xpos, int ypos) {
    tileSelector->attr0 = ypos | SPRITES_PALETTE_TYPE | TILESELECTOR_SPRITE_SHAPE;
    tileSelector->attr1 = xpos | TILESELECTOR_SPRITE_SIZE;
}

static void drawSprites(void) {
    DMA[3].src = shadow;
    DMA[3].dst = OAMMEM;
    DMA[3].cnt = 128*4 | DMA_ON;
}
static void drawMenu(Menu* menu, int selectorPosition) {
    int basex = 104;
    int basey = 56;
    menuSelector->attr0 = (basey + (8*selectorPosition)) | SPRITES_PALETTE_TYPE | MENUSELECTOR_SPRITE_SHAPE;
    menuSelector->attr1 = basex | MENUSELECTOR_SPRITE_SIZE;
    if (menu->attack) {
        menuAttack->attr0 = basey | SPRITES_PALETTE_TYPE | ATTACKMENU_SPRITE_SHAPE;
        menuAttack->attr1 = basex | ATTACKMENU_SPRITE_SIZE;
        basey += 8;
    }
    if (menu->item) {
        menuItem->attr0 = basey | SPRITES_PALETTE_TYPE | ITEMMENU_SPRITE_SHAPE;
        menuItem->attr1 = basex | ITEMMENU_SPRITE_SIZE;
        basey += 8;
    }
    if (menu->wait) {
        menuWait->attr0 = basey | SPRITES_PALETTE_TYPE | WAITMENU_SPRITE_SHAPE;
        menuWait->attr1 = basex | WAITMENU_SPRITE_SIZE;
        basey += 8;
    }
}
static void hideMenu(void) {
    menuAttack->attr0 = ATTR0_HIDE;
    menuItem->attr0 = ATTR0_HIDE;
    menuWait->attr0 = ATTR0_HIDE;
    menuSelector->attr0 = ATTR0_HIDE;
}
// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppStateMap(AppState *state) {
    hideMenu();
    drawTileSelector(state->tSelector->xpos * 16, state->tSelector->ypos * 16);
    drawSprites();
}
void drawAppStateMenu(AppState *state) {
    tileSelector->attr0 = ATTR0_HIDE;
    drawMenu(state->menu, state->menuSelectorPosition);
    drawSprites();

}
